version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: masjid-app
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - app-storage:/var/www/html/storage
      - app-db:/var/www/html/database
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: http://localhost:81

      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite

      CACHE_DRIVER: database
      QUEUE_CONNECTION: database
      SESSION_DRIVER: database

      BROADCAST_CONNECTION: pusher
    networks:
      - masjid-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: masjid-queue
    restart: unless-stopped
    command: php artisan queue:work --sleep=1 --tries=3 --timeout=90
    volumes:
      - app-storage:/var/www/html/storage
      - app-db:/var/www/html/database
    environment:
      APP_ENV: production
      APP_DEBUG: "false"

      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite

      CACHE_DRIVER: database
      QUEUE_CONNECTION: database
      SESSION_DRIVER: database
    depends_on:
      - app
    networks:
      - masjid-network

networks:
  masjid-network:
    driver: bridge

volumes:
  app-storage:
  app-db:
